### PR TITLE
Update image to v1.0.1-beta.1

### PR DESCRIPTION
**Pull request by johnbelamaric**

### CODE REVIEW

**Comment by johnbelamaric** [comment]
@efiacor I tagged a new release of the UI image and this is the PR to update it in the package. I will also need to update the installer to use the new package, but I will wait until the official 1.0.1 release to do that. Which means for now you will need to manually update the UI after the install by going into /tmp/kpt-pkg/nephio-webui (I think that's where it is) and updatign the tag and running `kpt live apply`. We need to figure out how to make this smoother.

**Comment by efiacor** [comment]
> @efiacor I tagged a new release of the UI image and this is the PR to update it in the package. I will also need to update the installer to use the new package, but I will wait until the official 1.0.1 release to do that. Which means for now you will need to manually update the UI after the install by going into /tmp/kpt-pkg/nephio-webui (I think that's where it is) and updatign the tag and running `kpt live apply`. We need to figure out how to make this smoother.

Thanks @johnbelamaric , will give it a go tomorrow and verify.

**Pull request merged**
